config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users 
  resources :users
  resources :teachers
  resources :semesters
  resources :lessons
  resources :students
  resources :classrooms
  resources :subjects
  resources :courses
  resources :departaments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    # user ||= User.new # guest user (not logged in)
    current_user = user.id
      if user.admin?
        can :manage, :all
      elsif user.teacher?
        can [:index, :show, :create, :destroy, :update], Classroom
        can [:index, :show, :create, :destroy, :update], Lesson
        can [:index, :show, :create], Teacher
        can [:index, :show], Semester
        can [:index, :show], Student
        can [:index, :show], User
        can [:index, :show], Subject
        can [:index, :show], Course
        can [:index, :show], Departament
      elsif user.standard?
        can [:index, :show, :create, :destroy, :update], Classroom
        can [:index, :show, :create, :destroy, :update], Student
        can [:index, :show, :create, :destroy, :update], Semester
        can [:index, :show, :create, :destroy, :update], Subject
        can [:index, :show], User
        can [:index, :show], Teacher
        can [:index, :show], Subject
        can [:index, :show], Departament
        can [:index, :show], Lesson
      end

      
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :subject
  has_many :student, through: :subscriptions
  belongs_to :semester

  validates :code, presence: true, uniqueness: true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :departament
  has_many :subjects, through: :course_subjects
  has_many :students
end

app/models/course_subject.rb
class CourseSubject < ApplicationRecord
  belongs_to :course
  belongs_to :subject
end

app/models/departament.rb
class Departament < ApplicationRecord
    has_many :courses
    has_many :subjects
   
    
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :classroom
  has_many :student, through: :presences
  validates :name, presence: true, uniqueness: true
end

app/models/presence.rb
class Presence < ApplicationRecord
  belongs_to :lesson
  belongs_to :student
end

app/models/semester.rb
class Semester < ApplicationRecord
    has_many :classrooms
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :course
  has_many :classroom, through: :subscriptions
  has_many :lesson, through: :presences

  validates :subscription, presence: true, uniqueness: true, length: { is: 9 }

  # class Student
  #   self.per_page = 10
  # end
  
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :departament
  has_many :courses, through: :course_subjects
  has_many :classrooms

  has_many :equivalent_subjects
  has_many :equivalences, :through => :equivalent_subjects
  
  has_many :equivalences, :class_name => "EquivalentSubject", :foreign_key => "equivalence_id"
  has_many :equivalent_subjects, :through => :equivalences, :source => :subject


  
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :classroom
  belongs_to :student
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :user
  belongs_to :departament
  has_many :classrooms
  validates :registration, presence: true, uniqueness: true,  length: { is: 9 }
end

app/models/user.rb
class User < ApplicationRecord
	mount_uploader :photo, PhotoUploader

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
	has_one :teacher
	
	
	validates :kind, presence: true

	delegate :can?, :cannot?, to: :ability
	
	def ability
		@ability ||= Ability.new(self)
	  end

	

	enum kind: {
		standard: 0,
		admin: 1,
		teacher: 2,
	}

	

    
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource :subject

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :departament_id)
    end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper

    def teachers_name
        if current_user
            @user = current_user
            if @user.teacher? 
                if @user.id
                    @teacher.name = @user.name
                end
            elsif @user.admin?
                



            end
        
        
        end
    end


end

app/helpers/users_helper.rb
module UsersHelper
    def user_kind_options
        [['Coordenador', :admin], ['Funcionário Administrativo', :standard], ['Professor', :teacher]]
  end
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  
  <div class="field">
    <%= form.label :departament_id, "Departamento" %>
    <%= form.collection_select :derpatament_id, Departament.all, :id, :name, prompt: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editar disciplina</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Ver', @subject %> |
<%= link_to 'Cancelar', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Disciplinas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Departamento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.name %></td>
        <td><%= subject.departament.name %></td>
        <td><%= link_to 'Ver', subject %></td>
        <%if can? :manage, Subject %>
          <td><%= link_to 'Editar', edit_subject_path(subject) %></td>
          <td><%= link_to 'Excluir', subject, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
        <% end %>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%if can? :create, Subject %>
  <%= link_to 'Adicionar disciplina', new_subject_path %>
<% end %>

app/views/subjects/new.html.erb
<h1>Adicionar disciplina</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Cancelar', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome da matéria:</strong>
  <%= @subject.name %>
</p>

<p>
  <strong>Departamento:</strong>
  <%= @subject.departament.name %>
</p>
<% if can? :manage, Subject %>
  <%= link_to 'Editar', edit_subject_path(@subject) %>
<% end %>
<%= link_to 'Voltar', subjects_path %>