config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users 
  resources :users
  resources :teachers
  resources :semesters
  resources :lessons
  resources :students
  resources :classrooms
  resources :subjects
  resources :courses
  resources :departaments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    # user ||= User.new # guest user (not logged in)
    current_user = user.id
      if user.admin?
        can :manage, :all
      elsif user.teacher?
        can [:index, :show, :create, :destroy, :update], Classroom
        can [:index, :show, :create, :destroy, :update], Lesson
        can [:index, :show, :create], Teacher
        can [:index, :show], Semester
        can [:index, :show], Student
        can [:index, :show], User
        can [:index, :show], Subject
        can [:index, :show], Course
        can [:index, :show], Departament
      elsif user.standard?
        can [:index, :show, :create, :destroy, :update], Classroom
        can [:index, :show, :create, :destroy, :update], Student
        can [:index, :show, :create, :destroy, :update], Semester
        can [:index, :show, :create, :destroy, :update], Subject
        can [:index, :show], User
        can [:index, :show], Teacher
        can [:index, :show], Subject
        can [:index, :show], Departament
        can [:index, :show], Lesson
      end

      
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :subject
  has_many :student, through: :subscriptions
  belongs_to :semester

  validates :code, presence: true, uniqueness: true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :departament
  has_many :subjects, through: :course_subjects
  has_many :students
end

app/models/course_subject.rb
class CourseSubject < ApplicationRecord
  belongs_to :course
  belongs_to :subject
end

app/models/departament.rb
class Departament < ApplicationRecord
    has_many :courses
    has_many :subjects
   
    
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :classroom
  has_many :student, through: :presences
  validates :name, presence: true, uniqueness: true
end

app/models/presence.rb
class Presence < ApplicationRecord
  belongs_to :lesson
  belongs_to :student
end

app/models/semester.rb
class Semester < ApplicationRecord
    has_many :classrooms
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :course
  has_many :classroom, through: :subscriptions
  has_many :lesson, through: :presences

  validates :subscription, presence: true, uniqueness: true, length: { is: 9 }

  # class Student
  #   self.per_page = 10
  # end
  
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :departament
  has_many :courses, through: :course_subjects
  has_many :classrooms

  has_many :equivalent_subjects
  has_many :equivalences, :through => :equivalent_subjects
  
  has_many :equivalences, :class_name => "EquivalentSubject", :foreign_key => "equivalence_id"
  has_many :equivalent_subjects, :through => :equivalences, :source => :subject


  
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :classroom
  belongs_to :student
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :user
  belongs_to :departament
  has_many :classrooms
  validates :registration, presence: true, uniqueness: true,  length: { is: 9 }
end

app/models/user.rb
class User < ApplicationRecord
	mount_uploader :photo, PhotoUploader

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
	has_one :teacher
	
	
	validates :kind, presence: true

	delegate :can?, :cannot?, to: :ability
	
	def ability
		@ability ||= Ability.new(self)
	  end

	

	enum kind: {
		standard: 0,
		admin: 1,
		teacher: 2,
	}

	

    
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper

    def teachers_name
        if current_user
            @user = current_user
            if @user.teacher? 
                if @user.id
                    @teacher.name = @user.name
                end
            elsif @user.admin?
                



            end
        
        
        end
    end


end

app/helpers/users_helper.rb
module UsersHelper
    def user_kind_options
        [['Coordenador', :admin], ['Funcionário Administrativo', :standard], ['Professor', :teacher]]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sistema administrativo UFF</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
      <%= link_to 'Home', root_path %>
      <%= link_to 'Ver todos os professores', teachers_path %>
      <%= link_to 'Ver semestres letivos', semesters_path %>
      <%= link_to 'Ver aulas',  lessons_path %>
      <%= link_to 'Alunos matrículados', students_path %>
      <%= link_to 'Ver disciplinas', subjects_path %>
      <%= link_to 'Cursos registrados', courses_path %>
      <%= link_to 'Departamentos', departaments_path %>
      <%= link_to 'Turmas', classrooms_path %>
      <%= link_to 'Usuários', users_path %>
    <%= link_to 'Perfil', current_user %>
    <% end %>

    <% if !current_user %>
     <%= link_to 'Login', new_user_session_path %>
    <% end %>


     
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>   
    <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Sistema administrativo UFF</h1>
    
<br>
<p>Fruitcake donut gummi bears. Sesame snaps gummi bears sugar plum bear claw tootsie roll croissant. Chupa chups sugar plum caramels liquorice. Marshmallow gummi bears liquorice chocolate bar cake dessert danish pudding oat cake.</p>
<p>Sweet roll chupa chups cookie jelly pie bonbon gummi bears jelly-o. Apple pie cotton candy pie. Icing cupcake pudding marshmallow.</p>
<p>Muffin caramels topping cake. Danish oat cake icing candy canes jelly beans jelly-o cotton candy halvah. Marzipan marzipan gingerbread caramels gummi bears sweet chocolate cake croissant caramels. Powder pie bonbon sweet pudding.</p>
<p>Muffin muffin cupcake dessert marzipan soufflé. Apple pie tiramisu powder. Pie ice cream pudding tart ice cream pie danish.</p>
<p>Gummies dragée cake cake. Cupcake lollipop candy liquorice cookie. Biscuit chocolate bear claw toffee ice cream pie carrot cake. Gingerbread cookie marshmallow dragée tootsie roll sweet sesame snaps cheesecake croissant.</p>